# Generated by Django 4.1.3 on 2022-11-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_cooluser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
